export const content = {
  zh: {
    nav: {
      home: "首页",
      about: "关于",
      skills: "技能",
      projects: "项目",
      experience: "经历",
      contact: "联系",
    },
    hero: {
      greeting: "你好，我是",
      name: "车行",
      role: "初级软件工程师 · 全栈开发（应届）",
      credentials: "UNSW · QS 全球前 20 / 澳大利亚第 1  ·  石河子大学 · 211 / 双一流",
      tagline:
        "新南威尔士大学（UNSW）信息技术硕士（2025 届），有课程项目与个人练习项目的全栈开发经历。独立完成 RAG 文档问答练习项目并完成公网部署；在 Capstone 小组中参与推荐系统的前后端开发。熟悉 Python、React、PostgreSQL、Docker 等常用技术，仍在持续巩固基础与工程能力。",
      ctaProjects: "查看项目",
      ctaContact: "联系我",
    },
    about: {
      title: "关于我",
      p1: "教育背景涵盖海外顶尖院校与国内重点高校：新南威尔士大学（UNSW）信息技术硕士（2025 届），QS 世界大学排名全球前 20、澳大利亚第 1；本科就读于石河子大学信息管理与信息系统专业（2015 – 2019），国家「211」「双一流」建设高校。",
      p2: "有课程项目与个人练习项目的全栈开发经历：独立完成 RAG 文档问答练习项目并完成公网部署；在 Capstone 小组中参与推荐系统的前后端开发。熟悉 Python、React、PostgreSQL、Docker 等常用技术，仍在持续巩固基础与工程能力。",
      eduTitle: "教育背景",
      edu: [
        {
          school: "新南威尔士大学（UNSW）",
          degree: "信息技术硕士",
          period: "2023 – 2025",
          note: "QS 世界大学排名全球前 20 · 澳大利亚第 1 · 澳洲八大（Group of Eight）",
        },
        {
          school: "石河子大学",
          degree: "信息管理与信息系统 学士",
          period: "2015 – 2019",
          note: "国家「211工程」「双一流」建设高校",
        },
      ],
    },
    skills: {
      title: "技术栈",
      familiar: "熟悉",
      exposure: "了解",
      familiarList: [
        "Python",
        "JavaScript",
        "React",
        "Vite",
        "FastAPI",
        "Flask",
        "PostgreSQL",
        "Docker",
        "ChromaDB",
        "LangChain",
      ],
      exposureList: ["Node.js", "scikit-learn", "Material UI", "OpenAI API"],
    },
    projects: {
      title: "精选项目",
      featured: "代表作",
      items: [
        {
          name: "X-TechInsight",
          subtitle: "全栈 RAG 技术文档问答平台",
          type: "个人项目",
          desc: "支持文档上传、向量检索、流式问答与引用溯源。前后端分离部署，公网可访问演示。",
          tags: ["React", "FastAPI", "ChromaDB", "LangChain", "OpenAI", "Render"],
          demo: "https://x-techinsight-web.onrender.com/index.html",
          highlights: [
            "端到端 RAG 链路：上传 → 切分 → Embedding → 检索 → 流式生成",
            "领域标签过滤检索，降低跨领域串答",
            "SSE 流式输出 + [Source N] 引用溯源",
          ],
        },
        {
          name: "Avocado",
          subtitle: "AI 团队–项目智能推荐系统",
          type: "UNSW Capstone",
          desc: "基于技能画像互补性的推荐系统，帮助导师分配项目、团队匹配合适课题。",
          tags: ["React", "Flask", "PostgreSQL", "scikit-learn", "Docker"],
          demo: null,
          highlights: [
            "Flask 后端 API + React 前端全栈协作开发",
            "PostgreSQL 数据建模与 Docker Compose 部署",
            "Random Forest 推荐算法集成与功能测试",
          ],
        },
      ],
    },
    experience: {
      title: "工作经历",
      items: [
        {
          role: "微信部 & 微博部总监",
          org: "石河子大学团委新媒体工作室",
          period: "2015 – 2019",
          desc: "校园新媒体运营，微博粉丝一年内增长 1000+。",
        },
        {
          role: "城市主管（新疆渠道）",
          org: "新浪微博 · 新浪校园",
          period: "2017 – 2018",
          desc: "高校活动审核与现场技术保障。",
        },
        {
          role: "头条学院学员",
          org: "字节跳动（今日头条）",
          period: "2017",
          desc: "新媒体内容创作，单篇浏览量 66 万+。",
        },
      ],
    },
    contact: {
      title: "保持联系",
      subtitle: "应届硕士，目前正在寻找全职软件工程师岗位，欢迎联系与交流。",
      email: "ian.kabutack@gmail.com",
      phone: "150-4385-7875",
      sayHello: "发送邮件",
    },
    footer: "© 2026 车行 · Built with React + Vite",
  },
  en: {
    nav: {
      home: "Home",
      about: "About",
      skills: "Skills",
      projects: "Projects",
      experience: "Experience",
      contact: "Contact",
    },
    hero: {
      greeting: "Hi, my name is",
      name: "Ian Che",
      role: "Junior Software Engineer · Full Stack · Recent Graduate",
      credentials: "UNSW · QS Top 20 / #1 in Australia  ·  Shihezi Univ. · Project 211 & Double First-Class",
      tagline:
        "Recent UNSW Master of IT graduate (2025) with hands-on practice in full stack web development through coursework, a capstone team project, and a personal RAG learning project. Comfortable with Python, React, PostgreSQL, and Docker; still building depth in software engineering fundamentals and production practices.",
      ctaProjects: "View Projects",
      ctaContact: "Get in Touch",
    },
    about: {
      title: "About Me",
      p1: "Education spans a top Australian university and a leading Chinese institution: Master of IT from UNSW (2025), QS World University Rankings Top 20 (#1 in Australia); B.S. in Information Management & Information Systems from Shihezi University (2015 – 2019), a Project 211 & Double First-Class university in China.",
      p2: "Hands-on full stack experience through coursework and projects: built and deployed a personal RAG documentation Q&A platform; contributed to frontend and backend development on a capstone recommendation system. Comfortable with Python, React, PostgreSQL, and Docker; still building depth in software engineering fundamentals.",
      eduTitle: "Education",
      edu: [
        {
          school: "University of New South Wales (UNSW)",
          degree: "Master of Information Technology",
          period: "2023 – 2025",
          note: "QS World University Rankings Top 20 · #1 in Australia · Group of Eight (Go8)",
        },
        {
          school: "Shihezi University",
          degree: "B.S. Information Management & Information Systems",
          period: "2015 – 2019",
          note: "Project 211 & Double First-Class university (China)",
        },
      ],
    },
    skills: {
      title: "Tech Stack",
      familiar: "Familiar",
      exposure: "Exposure",
      familiarList: [
        "Python",
        "JavaScript",
        "React",
        "Vite",
        "FastAPI",
        "Flask",
        "PostgreSQL",
        "Docker",
        "ChromaDB",
        "LangChain",
      ],
      exposureList: ["Node.js", "scikit-learn", "Material UI", "OpenAI API"],
    },
    projects: {
      title: "Featured Projects",
      featured: "Featured",
      items: [
        {
          name: "X-TechInsight",
          subtitle: "Full Stack RAG Documentation Platform",
          type: "Personal Project",
          desc: "Document upload, vector retrieval, streaming Q&A with source citations. Split deployment with a public live demo.",
          tags: ["React", "FastAPI", "ChromaDB", "LangChain", "OpenAI", "Render"],
          demo: "https://x-techinsight-web.onrender.com/index.html",
          highlights: [
            "End-to-end RAG: upload → chunk → embed → retrieve → stream",
            "Domain-tagged retrieval to reduce cross-domain noise",
            "SSE streaming with [Source N] citations",
          ],
        },
        {
          name: "Avocado",
          subtitle: "AI Team–Project Recommendation System",
          type: "UNSW Capstone",
          desc: "Matches student teams to capstone projects by skill complementarity for tutors and teams.",
          tags: ["React", "Flask", "PostgreSQL", "scikit-learn", "Docker"],
          demo: null,
          highlights: [
            "Flask APIs + React frontend in a team setting",
            "PostgreSQL schema design & Docker Compose",
            "Random Forest recommendation integration & testing",
          ],
        },
      ],
    },
    experience: {
      title: "Experience",
      items: [
        {
          role: "Director, WeChat & Weibo",
          org: "Shihezi University New Media Studio",
          period: "2015 – 2019",
          desc: "Campus social media; grew Weibo by 1,000+ in one year.",
        },
        {
          role: "City Manager, Xinjiang",
          org: "Sina Weibo Campus",
          period: "2017 – 2018",
          desc: "Event approvals and on-site technical support.",
        },
        {
          role: "Trainee",
          org: "ByteDance Toutiao Academy",
          period: "2017",
          desc: "Content reaching 660K+ views on one article.",
        },
      ],
    },
    contact: {
      title: "Get In Touch",
      subtitle: "Recent graduate seeking full-time software engineering roles. Feel free to reach out.",
      email: "ian.kabutack@gmail.com",
      phone: "+86 150-4385-7875",
      sayHello: "Say Hello",
    },
    footer: "© 2026 Ian Che · Built with React + Vite",
  },
};
